#!/usr/bin/env bash

config_path="$HOME/.config/webspeeddial/config.json"
if test -f "$config_path"; then
    config=$(cat "$config_path")
else
    config="{\"runner\": \"fzf\", \"bookmarks\": []}"
    mkdir -p "$HOME/.config/webspeeddial"
    touch "$config_path"
    echo "$config" > "$config_path"
fi
echo $config

runner=$(echo $config | jq ".runner")

bookmarks=$(echo $config | jq ".bookmarks")
selections=""
for i in $bookmarks; do
    left=$(echo "$i" | jq ".name")
    right=$"\n"
    selections+="${left}${right}"
done

echo "$selections" | fzf
